name: Continuous Deployment with Docker Test

on:
  push:

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -f Dockerfile_test .

    - name: Run Docker Container and Output Test Results
      run: |
        docker run gptpythonwrapper 
