name: Continuous Integration testing with pytest
on:
  push:
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
  # Get src code
    - name: Check out repository
      uses: actions/checkout@v4
  # Setup python
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
  # Creates and activates a virtual environment
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    # Installs dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Run Test
    - name: Run pytest
      uses: pavelzw/pytest-action@v2.1.0
