name: Continuous Integration testing with pytest
on:
  push:
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
  # Get src code
    - name: Check out repository
      uses: actions/checkout@v4
    # Run Test
    - name: Pytest
      uses: microsoft/action-python@0.7.0
      with:          
        testing: true
