name: Continuous Integration testing with pytest
on:
  push:
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Run pytest
      uses: pavelzw/pytest-action@v2.1.0
